language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t varunkverma/docker-react  -f Dockerfile.dev .

script:
    - docker run -e CI=true varunkverma/docker-react exec npm run test